export const APP_ROUTES = {
  TABLE: 'table',
  BUTTON: 'button',
  MESSAGE: 'message',
  TOAST: 'toast',
  ICON: 'icon',
  SELECT: 'select',
  DIVIDER: 'divider',
  TOGGLE: 'toggle',
  RADIO: 'radio',
  INPUT: 'input',
  SPINNER: 'spinner',
  CHIP: 'chip',
  TOOLTIP: 'tooltip',
  CHECKBOX: 'checkbox',
  CARD: 'card',
  ICON_FIELD: 'icon-field',
  LIST: 'list',
  PAGINATOR: 'paginator',
  SLIDER: 'slider',
  DATEPICKER: 'date-picker',
  ACCORDION: 'accordion',
  DIALOG: 'dialog',
  SEARCH: 'search',
  TABS: 'tabs',
  BREADCRUMB: 'breadcrumb',
  CONTEXTMENU: 'context-menu',
  GRID: 'grid',
  NAVBAR: 'navbar',
  NAVBAR: 'navbar',
  POPOVER: 'popover',
  SCROLL_TOP_DOWN: 'scroll-top-down',
};
};
