import { LitElement, PropertyValues } from 'lit';
import { DcxCalendarDayCell, DcxCalendarDeleteScope, DcxCalendarEvent, DcxCalendarEventType, DcxCalendarMonthSummary, DcxCalendarRecurrence, DcxCalendarSelectionMode, DcxCalendarView, DcxCalendarWeekDay } from '../../core/interfaces/calendar';
import { DcxRadioOption } from '../../core/interfaces/radio';
export type CalendarModalMode = 'create' | 'edit' | 'delete' | null;
export interface CalendarFormModel {
    title: string;
    date: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    type: DcxCalendarEventType;
    description: string;
    recurrence: DcxCalendarRecurrence;
}
export declare class DcxWebCalendar extends LitElement {
    static styles: import('lit').CSSResult;
    accessor view: DcxCalendarView;
    accessor activeDate: Date;
    accessor events: DcxCalendarEvent[];
    accessor selectionMode: DcxCalendarSelectionMode;
    accessor selectedDate: Date | null;
    accessor rangeStart: Date | null;
    accessor rangeEnd: Date | null;
    accessor disabled: boolean;
    accessor allowCreate: boolean;
    accessor allowEdit: boolean;
    accessor allowDelete: boolean;
    accessor dayMaxVisibleEvents: number;
    accessor weekStartHour: number;
    accessor weekEndHour: number;
    accessor showFooter: boolean;
    accessor ariaLabel: string;
    get today(): Date;
    accessor localActiveDate: Date;
    accessor localEvents: DcxCalendarEvent[];
    accessor localSelectedDate: Date | null;
    accessor localRangeStart: Date | null;
    accessor localRangeEnd: Date | null;
    accessor selectedEventId: string | null;
    accessor modalMode: CalendarModalMode;
    accessor deleteScope: DcxCalendarDeleteScope;
    accessor formError: string;
    accessor eventForm: CalendarFormModel;
    private lastFocusedBeforeModal;
    readonly weekLabels: string[];
    readonly eventTypeOptions: {
        value: DcxCalendarEventType;
        label: string;
    }[];
    readonly recurrenceOptions: {
        value: DcxCalendarRecurrence;
        label: string;
    }[];
    readonly deleteScopeOptions: DcxRadioOption[];
    connectedCallback(): void;
    disconnectedCallback(): void;
    willUpdate(changedProperties: PropertyValues<this>): void;
    updated(changedProperties: PropertyValues<this>): void;
    get isMonthView(): boolean;
    get isWeekView(): boolean;
    get isYearView(): boolean;
    get isMiniView(): boolean;
    get isRangeMode(): boolean;
    get showMonthEvents(): boolean;
    get footerMode(): 'range' | 'default';
    get monthLabel(): string;
    get weekLabel(): string;
    get yearLabel(): string;
    get weekHours(): number[];
    get monthWeeks(): DcxCalendarDayCell[][];
    get weekDays(): DcxCalendarWeekDay[];
    get yearMonths(): DcxCalendarMonthSummary[];
    get selectedEvent(): DcxCalendarEvent | null;
    setDeleteScope(value: string | null): void;
    previous(): void;
    next(): void;
    goToToday(): void;
    selectYearMonth(monthIndex: number): void;
    selectDay(day: DcxCalendarDayCell): void;
    applyRange(): void;
    clearRange(): void;
    private emitRangeChange;
    openEvent(event: DcxCalendarEvent): void;
    openDayOverflow(day: DcxCalendarDayCell): void;
    openCreateModal(date?: Date): void;
    openEditModal(event: DcxCalendarEvent): void;
    openDeleteModal(): void;
    closeOverlay(): void;
    closeSelectedEvent(): void;
    saveEvent(): void;
    confirmDelete(): void;
    handleEscape(): void;
    private handleDocumentKeydown;
    private handleModalTab;
    private getFocusableElements;
    private focusElement;
    private emitEventCreate;
    private emitEventUpdate;
    private emitEventDelete;
    getVisibleEvents(day: DcxCalendarDayCell): DcxCalendarEvent[];
    getOverflowCount(day: DcxCalendarDayCell): number;
    getWeekSlotEvents(date: Date, hour: number): DcxCalendarEvent[];
    getEventClass(type: DcxCalendarEventType): string;
    formatDayLabel(value: Date): string;
    formatTimeRange(event: DcxCalendarEvent): string;
    formatRecurrenceLabel(value: DcxCalendarRecurrence | undefined): string;
    private setActiveDate;
    private buildMonthGrid;
    private getEventsForDate;
    private createEmptyForm;
    private createFormFromEvent;
    private formToEvent;
    private toEventDraft;
    private cloneEvents;
    private normalizeDate;
    private startOfWeek;
    private addDays;
    private startOfDay;
    private isSameDate;
    private toDateInputValue;
    private toTimeInputValue;
    private formatTime;
    private capitalize;
    render(): import('lit-html').TemplateResult<1>;
}
declare global {
    interface HTMLElementTagNameMap {
        'dcx-web-calendar': DcxWebCalendar;
    }
}
