import { LitElement } from 'lit';
import { CalendarDay, DateFormat, FirstDayOfWeek, DatePickerProps } from '../../core/interfaces';
export declare class DcxWebDatePicker extends LitElement implements DatePickerProps {
    static styles: import('lit').CSSResult;
    accessor selectedDate: Date | null;
    accessor selectedDates: Date[];
    accessor multiSelect: boolean;
    accessor rangeSelect: boolean;
    accessor startDate: Date | null;
    accessor endDate: Date | null;
    accessor minDate: Date | null;
    accessor maxDate: Date | null;
    accessor disabled: boolean;
    accessor placeholder: string;
    accessor dateFormat: DateFormat;
    accessor firstDayOfWeek: FirstDayOfWeek;
    private accessor _currentMonth;
    private accessor _isOpen;
    private accessor _mode;
    private accessor _yearPageStart;
    private accessor _focusedDate;
    get isOpen(): boolean;
    get isMonthMode(): boolean;
    get isYearMode(): boolean;
    get isCalendarMode(): boolean;
    get currentMonth(): Date;
    get monthName(): string;
    get yearNumber(): number;
    get yearsList(): number[];
    get formattedSelectedDate(): string;
    get showClearButton(): boolean;
    get weekDays(): string[];
    get calendarDays(): CalendarDay[];
    get calendarWeeks(): CalendarDay[][];
    get gridAriaLabel(): string;
    readonly labels: {
        clearDate: string;
        previous: string;
        next: string;
        selectMonth: string;
        selectYear: string;
        today: string;
        goToToday: string;
    };
    readonly monthsList: string[];
    get monthsIndexes(): number[];
    private readonly dateFormatPatterns;
    private readonly _docClickHandler;
    connectedCallback(): void;
    disconnectedCallback(): void;
    protected updated(changedProperties: Map<PropertyKey, unknown>): void;
    private _onDocumentClick;
    onTriggerKeydown(event: KeyboardEvent): void;
    onGridKeydown(event: KeyboardEvent, day: CalendarDay): void;
    isFocusedDay(day: CalendarDay): boolean;
    toggleCalendar(): void;
    closeCalendar(): void;
    previousYear(): void;
    nextYear(): void;
    previousMonth(): void;
    nextMonth(): void;
    openMonthSelector(): void;
    openYearSelector(): void;
    selectMonth(index: number): void;
    selectYear(year: number): void;
    applyDate(): void;
    selectDate(day: CalendarDay): void;
    clearDate(event?: Event): void;
    goToToday(): void;
    private _moveFocus;
    private _moveFocusToStartOfWeek;
    private _moveFocusToEndOfWeek;
    private _defaultFocusDate;
    private _focusDayCell;
    private _formatDate;
    private _formatRangeDate;
    private _formatMultipleDate;
    private _formatSingleDate;
    private _calculateDateSelectionState;
    private _calculateRangeState;
    private _calculateMultiState;
    private _calculateSingleState;
    private _handleRangeSelection;
    private _handleMultiSelection;
    private _handleSingleSelection;
    private _isDateDisabled;
    private _emitEvent;
    render(): import('lit-html').TemplateResult<1>;
}
declare global {
    interface HTMLElementTagNameMap {
        'dcx-web-datepicker': DcxWebDatePicker;
    }
}
