import { BorderStyleCard, ShadowPresetCard } from '../interfaces';
export declare const TITLE_DEFAULT = "T\u00EDtulo de la carta";
export declare const SUBTITLE = "Subt\u00EDtulo de la carta";
export declare const IMAGE = "https://picsum.photos/360/240";
export declare const IMAGE_ALT = "";
export declare const MAX_CONTENT_WIDTH = "560px";
export declare const MAX_IMAGE_WIDTH = "100%";
export declare const BORDERED = false;
export declare const ACCENT = false;
export declare const BORDER_WIDTH = 1;
export declare const BORDER_STYLE_DEFAULT: BorderStyleCard;
export declare const BORDER_STYLE_LIST: BorderStyleCard[];
export declare const INTERACTIVE = true;
export declare const SHADOW_DEFAULT: ShadowPresetCard;
export declare const SHADOW_LIST: ShadowPresetCard[];
export declare const DEFAULTARGS: {
    align: "center" | "start" | "end";
    bordered: boolean;
    borderStyle: "solid";
    borderWidth: number;
    disabled: boolean;
    image: string;
    imageAlt: string;
    interactive: boolean;
    layout: "vertical" | "horizontal";
    maxContentWidth: string;
    maxImageWidth: string;
    shadow: 1;
    size: "xl" | "s" | "m" | "l" | "auto";
    subtitle: string;
    title: string;
    accent: boolean;
};
