import { LitElement, PropertyValues } from 'lit';
import { DcxEditorToolbarAction, DcxEditorToolbarItem } from '../../core/interfaces';
export declare class DcxWebEditor extends LitElement {
    static styles: import('lit').CSSResult;
    accessor id: string;
    accessor value: string;
    accessor label: string;
    accessor placeholder: string;
    accessor disabled: boolean;
    accessor readonly: boolean;
    accessor required: boolean;
    accessor isInvalid: boolean;
    accessor errorMessage: string;
    accessor ariaLabel: string | null;
    accessor ariaDescribedBy: string | null;
    accessor minHeight: string;
    accessor toolbarActions: DcxEditorToolbarAction[];
    accessor focused: boolean;
    accessor activeToolbarActions: Set<DcxEditorToolbarAction>;
    private accessor _pendingToolbarActions;
    private _viewReady;
    private _savedRange;
    private readonly _onDocumentSelectionChange;
    connectedCallback(): void;
    disconnectedCallback(): void;
    protected firstUpdated(): void;
    protected updated(changed: PropertyValues<this>): void;
    get editorEl(): HTMLElement | null;
    get errorId(): string;
    get describedBy(): string | null;
    get isDisabled(): boolean;
    get editorClasses(): string;
    get toolbarItems(): DcxEditorToolbarItem[];
    private emit;
    onInput(): void;
    onFocus(): void;
    onBlur(): void;
    applyCommand(item: DcxEditorToolbarItem): void;
    onToolbarMouseDown(event: MouseEvent): void;
    onToolbarButtonClick(item: DcxEditorToolbarItem): void;
    onEditorSelectionChange(): void;
    onBeforeInput(event: InputEvent): void;
    isToolbarActionActive(action: DcxEditorToolbarAction): boolean;
    saveSelection(): void;
    private getActiveSelection;
    private restoreSelection;
    private applyToolbarAction;
    private wrapSelection;
    private wrapSelectionWithList;
    private replaceSelectionWithPlainText;
    private cleanupFormattingAtRange;
    private getPlainText;
    private getEditableRange;
    private moveSelectionAfter;
    private moveSelectionToEnd;
    private togglePendingToolbarAction;
    private togglePendingListAction;
    private togglePendingInlineAction;
    private toggleSetValue;
    private insertTextWithToolbarState;
    private getPendingListAction;
    private insertNodeAtRange;
    private insertNodeInList;
    private wrapTextNodeWithPendingInlineFormats;
    private getCurrentListItem;
    private escapeInlineFormat;
    private isInlineActionActive;
    private getClosestInlineFormatWrapper;
    private updateActiveToolbarActions;
    private getSelectionContextNode;
    private hasAncestorTag;
    private getClosestAncestorTag;
    private isNodeEmpty;
    private selectionBelongsToEditor;
    private updateValueFromEditor;
    private isEditorFocused;
    private renderValue;
    private sanitizeHtml;
    render(): import('lit-html').TemplateResult<1>;
}
declare global {
    interface HTMLElementTagNameMap {
        'dcx-web-editor': DcxWebEditor;
    }
}
